# Konfigurasi untuk Netlify
[build]
  # Perintah untuk menginstal dependensi Netlify Functions
  command = "npm install"
  # Folder yang berisi file statis (HTML, CSS, JS)
  publish = "public"
  # Folder tempat Netlify akan mencari Functions
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
